name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Build Docker Image
      run: docker build -t my-speakx-assignment:${{ github.sha }} .
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push to Docker Hub
      run: |
        docker tag my-speakx-assignment:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/my-speakx-assignment:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-speakx-assignment:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-speakx-assignment:latest
          docker stop my-speakx-assignment || true
          docker rm my-speakx-assignment || true
          docker run -d \
            --name my-speakx-assignment \
            -p 3000:3000 \
            ${{ secrets.DOCKERHUB_USERNAME }}/my-speakx-assignment:latest
