name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mobile-backend:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/mobile-backend:latest
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          # Pull latest Docker image
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/mobile-backend:latest
          
          # Run new container
          docker run -d \
            --name mobile-backend \
            -p 3000:3000 \
            ${{ secrets.DOCKERHUB_USERNAME }}/mobile-backend:latest
